# pipeline for TestApplication.

groups:
- name: dotnet-resource-test-application
  jobs:
  - build-service
  - deploy-service

resource_types:
- name: dotnet
  type: docker-image
  source:
    repository: miclip/dotnet-resource
    tag: "latest"

resources:
- name: app-repo
  type: git
  source:
    uri: https://github.com/miclip/dotnet-resource-test-application.git
    branch: master

- name: pws-development
  type: cf
  source:
    api: https://api.run.pivotal.io
    organization: {{cf-org}}
    username: {{cf-username}}
    password: {{cf-password}}
    skip_cert_check: false
    space: development  

- name: dotnet-build-push-nuget
  type: dotnet 
  source:
    framework: netcoreapp2.1
    runtime: ubuntu.14.04-x64
    nuget_source: https://www.myget.org/F/dotnet-resource-test/api/v3/index.json
    nuget_apikey: {{nuget_apikey}}
    nuget_timeout: 600

- name: app-nuget
  type: dotnet 
  source:
    nuget_source: https://www.myget.org/F/dotnet-resource-test/api/v3/index.json
    nuget_apikey: {{nuget_apikey}}
    nuget_timeout: 600
    package_id: DotnetResource.TestApplication
    prerelease: true

  
jobs:
- name: build-service
  public: true
  serial: true
  plan:
  - get: app-repo
    trigger: true
  - put: dotnet-build-push-nuget
    params:
     project: app-repo/DotnetResource.sln
     test_filter: "*.Tests.csproj"
     version: "1.0.*"
     package_type: Application
- name: deploy-service
  public: true
  serial: true
  plan:
  - get: app-nuget
    trigger: true
  - put: pws-development
    params:
      manifest: app-nuget/DotnetResource.TestApplication/manifest.yml
      path: app-nuget/DotnetResource.TestApplication
      current_app_name: dotnetresourcetestapp

     
    
  
